scenario: target_sentence
target_sentence: "HELLO FROM THE EVOLUTION LAB"

population_size: 400
generations: 3000
stagnation_patience: 100

base_mutation_rate: 0.05
low_diversity_factor: 0.20
high_diversity_factor: 0.50
anneal_factor: 0.998
micro_threshold: 3
micro_mutation_rate: 0.20
random_sentence_length: 30
