scenario: ngram_fluency

# parámetros del escenario
order: 2          # 2 = bigramas
length: 30

# parámetros del motor
population_size: 600
generations: 4000
stagnation_patience: 200

base_mutation_rate: 0.05
low_diversity_factor: 0.20
high_diversity_factor: 0.50
anneal_factor: 0.998
micro_threshold: 5
micro_mutation_rate: 0.30
